task :default => [:test]

task :test do
  Dir.foreach("tests") do |t|
    next unless t =~ /^.*_test.rb$/
    ruby File.join("tests",t)
  end
end

task :clean do
  system "rm -f tests/output.rb"
  system "rm -f core"
end